# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: Tazama Landscape

url: http://127.0.0.1:8000

colors:
  color1: "rgba(43, 110, 89, 1)"
  color2: "rgba(37, 95, 77, 1)"
  color3: "rgba(160, 218, 200, 1)"
  color4: "rgba(84, 188, 156, 1)"
  color5: "rgba(43, 110, 89, 1)"
  color6: "rgba(84, 188, 156, 1)"
  color7: "rgba(180, 219, 255, 1)"

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Graduated

footer:
  links:
    github: "https://github.com/tazama-lf"
    homepage: "https://tazama.org/"
    linkedin: "https://www.linkedin.com/company/tazama-org/"
    slack: "https://www.slack.tazama.org/"
    youtube: "https://www.youtube.com/@Tazama-org"
  logo: "https://tazama.org/logo.svg"

grid_items_size: large

groups:
  - name: All Groups
    categories:
      - Tazama Project Participants
      - Tazama Project Adopters
      - Tazama Project Funders
      - Related Organizations
header:
  links:
    github: "https://github.com/tazama-lf"
  logo: "https://tazama.org/logo.svg"

screenshot_width: 1500
